/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import distributor.*;
import subscriber.*;
import javax.swing.*;

public class DistributorUI extends JFrame {
    private Distributor distributor;
    
    public DistributorUI() {
        initComponents();
    }
       
    public void setDistributor(Distributor distributor) {
        this.distributor = distributor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addSubscriberButton = new javax.swing.JButton();
        addJournalButton = new javax.swing.JButton();
        addSubscriptionButton = new javax.swing.JButton();
        saveStateButton = new javax.swing.JButton();
        loadStateButton = new javax.swing.JButton();
        listIncompleteButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        searchSubscriberButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        issnField = new javax.swing.JTextField();
        searchJournalButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idField2 = new javax.swing.JTextField();
        listSubscriberButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        listJournalButton = new javax.swing.JButton();
        issnField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        issnField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        listSendingOrdersButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        monthField2 = new javax.swing.JTextField();
        yearField2 = new javax.swing.JTextField();
        listAllSendingOrdersButton = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        reportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(159, 29));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1049, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("DISTRIBUTOR");

        addSubscriberButton.setBackground(new java.awt.Color(153, 0, 0));
        addSubscriberButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        addSubscriberButton.setForeground(new java.awt.Color(255, 255, 255));
        addSubscriberButton.setText("ADD SUBSCRIBER");
        addSubscriberButton.setMaximumSize(new java.awt.Dimension(159, 29));
        addSubscriberButton.setMinimumSize(new java.awt.Dimension(159, 29));
        addSubscriberButton.setPreferredSize(new java.awt.Dimension(159, 29));
        addSubscriberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubscriberButtonActionPerformed(evt);
            }
        });

        addJournalButton.setBackground(new java.awt.Color(153, 0, 0));
        addJournalButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        addJournalButton.setForeground(new java.awt.Color(255, 255, 255));
        addJournalButton.setText("ADD JOURNAL");
        addJournalButton.setMaximumSize(new java.awt.Dimension(159, 29));
        addJournalButton.setMinimumSize(new java.awt.Dimension(159, 29));
        addJournalButton.setPreferredSize(new java.awt.Dimension(159, 29));
        addJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJournalButtonActionPerformed(evt);
            }
        });

        addSubscriptionButton.setBackground(new java.awt.Color(153, 0, 0));
        addSubscriptionButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        addSubscriptionButton.setForeground(new java.awt.Color(255, 255, 255));
        addSubscriptionButton.setText("ADD SUBSCRIPTION");
        addSubscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubscriptionButtonActionPerformed(evt);
            }
        });

        saveStateButton.setBackground(new java.awt.Color(153, 0, 0));
        saveStateButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        saveStateButton.setForeground(new java.awt.Color(255, 255, 255));
        saveStateButton.setText("SAVE STATE");
        saveStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStateButtonActionPerformed(evt);
            }
        });

        loadStateButton.setBackground(new java.awt.Color(153, 0, 0));
        loadStateButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        loadStateButton.setForeground(new java.awt.Color(255, 255, 255));
        loadStateButton.setText("LOAD STATE");
        loadStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadStateButtonActionPerformed(evt);
            }
        });

        listIncompleteButton.setBackground(new java.awt.Color(153, 0, 0));
        listIncompleteButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        listIncompleteButton.setForeground(new java.awt.Color(255, 255, 255));
        listIncompleteButton.setText("LIST INCOMPLETE PAYMENTS");
        listIncompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIncompleteButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("SUBCRIBER ID");

        idField.setBackground(new java.awt.Color(255, 255, 255));

        searchSubscriberButton.setBackground(new java.awt.Color(153, 0, 0));
        searchSubscriberButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        searchSubscriberButton.setForeground(new java.awt.Color(255, 255, 255));
        searchSubscriberButton.setText("SEARCH SUBSCRIBER");
        searchSubscriberButton.setMaximumSize(new java.awt.Dimension(159, 29));
        searchSubscriberButton.setMinimumSize(new java.awt.Dimension(159, 29));
        searchSubscriberButton.setPreferredSize(new java.awt.Dimension(159, 29));
        searchSubscriberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSubscriberButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("JOURNAL ISSN");

        issnField.setBackground(new java.awt.Color(255, 255, 255));

        searchJournalButton.setBackground(new java.awt.Color(153, 0, 0));
        searchJournalButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        searchJournalButton.setForeground(new java.awt.Color(255, 255, 255));
        searchJournalButton.setText("SEARCH JOURNAL");
        searchJournalButton.setMaximumSize(new java.awt.Dimension(159, 29));
        searchJournalButton.setMinimumSize(new java.awt.Dimension(159, 29));
        searchJournalButton.setPreferredSize(new java.awt.Dimension(159, 29));
        searchJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJournalButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("SUBSCRIBER ID");

        idField2.setBackground(new java.awt.Color(255, 255, 255));

        listSubscriberButton.setBackground(new java.awt.Color(153, 0, 0));
        listSubscriberButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        listSubscriberButton.setForeground(new java.awt.Color(255, 255, 255));
        listSubscriberButton.setText("LIST SUBSCRIPTIONS OF SUBSCRIBER");
        listSubscriberButton.setMaximumSize(new java.awt.Dimension(159, 29));
        listSubscriberButton.setMinimumSize(new java.awt.Dimension(159, 29));
        listSubscriberButton.setPreferredSize(new java.awt.Dimension(159, 29));
        listSubscriberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSubscriberButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("JOURNAL ISSN");

        listJournalButton.setBackground(new java.awt.Color(153, 0, 0));
        listJournalButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        listJournalButton.setForeground(new java.awt.Color(255, 255, 255));
        listJournalButton.setText("LIST SUBSCRIPTIONS OF JOURNAL");
        listJournalButton.setMaximumSize(new java.awt.Dimension(159, 29));
        listJournalButton.setMinimumSize(new java.awt.Dimension(159, 29));
        listJournalButton.setPreferredSize(new java.awt.Dimension(159, 29));
        listJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listJournalButtonActionPerformed(evt);
            }
        });

        issnField2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("JOURNAL ISSN");

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("MONTH");

        yearField.setBackground(new java.awt.Color(255, 255, 255));

        issnField3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("YEAR");

        monthField.setBackground(new java.awt.Color(255, 255, 255));

        listSendingOrdersButton.setBackground(new java.awt.Color(153, 0, 0));
        listSendingOrdersButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        listSendingOrdersButton.setForeground(new java.awt.Color(255, 255, 255));
        listSendingOrdersButton.setText("LIST SENDING ORDERS");
        listSendingOrdersButton.setMaximumSize(new java.awt.Dimension(159, 29));
        listSendingOrdersButton.setMinimumSize(new java.awt.Dimension(159, 29));
        listSendingOrdersButton.setPreferredSize(new java.awt.Dimension(159, 29));
        listSendingOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSendingOrdersButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("MONTH");

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("YEAR");

        monthField2.setBackground(new java.awt.Color(255, 255, 255));

        yearField2.setBackground(new java.awt.Color(255, 255, 255));

        listAllSendingOrdersButton.setBackground(new java.awt.Color(153, 0, 0));
        listAllSendingOrdersButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        listAllSendingOrdersButton.setForeground(new java.awt.Color(255, 255, 255));
        listAllSendingOrdersButton.setText("LIST ALL SENDING ORDERS");
        listAllSendingOrdersButton.setMaximumSize(new java.awt.Dimension(159, 29));
        listAllSendingOrdersButton.setMinimumSize(new java.awt.Dimension(159, 29));
        listAllSendingOrdersButton.setPreferredSize(new java.awt.Dimension(159, 29));
        listAllSendingOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllSendingOrdersButtonActionPerformed(evt);
            }
        });

        message.setBackground(new java.awt.Color(153, 0, 0));
        message.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        message.setForeground(new java.awt.Color(153, 0, 0));

        reportButton.setBackground(new java.awt.Color(153, 0, 0));
        reportButton.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        reportButton.setForeground(new java.awt.Color(255, 255, 255));
        reportButton.setText("REPORT");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addSubscriberButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(addJournalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(addSubscriptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(loadStateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(saveStateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(listIncompleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(reportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(issnField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(issnField3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(monthField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(yearField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(issnField2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(idField2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listSubscriberButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(searchJournalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchSubscriberButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listSendingOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listAllSendingOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listJournalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(message, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addSubscriberButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchSubscriberButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchJournalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issnField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(addJournalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listSubscriberButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSubscriptionButton)
                    .addComponent(idField2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listJournalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issnField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listIncompleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(issnField3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(monthField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listSendingOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveStateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listAllSendingOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadStateButton))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportButton)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSubscriberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubscriberButtonActionPerformed
        SubscriberUI subscriber = new SubscriberUI();
        subscriber.setDistributor(distributor);
        subscriber.setVisible(true);
        subscriber.pack();
        subscriber.setLocationRelativeTo(null);
    }//GEN-LAST:event_addSubscriberButtonActionPerformed

    private void addJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJournalButtonActionPerformed
        JournalUI journal = new JournalUI();
        journal.setDistributor(distributor);
        journal.setVisible(true);
        journal.pack();
        journal.setLocationRelativeTo(null);
    }//GEN-LAST:event_addJournalButtonActionPerformed

    private void addSubscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubscriptionButtonActionPerformed
        SubscriptionUI subscription = new SubscriptionUI();
        subscription.setDistributor(distributor);
        subscription.setVisible(true);
        subscription.pack();
        subscription.setLocationRelativeTo(null);
    }//GEN-LAST:event_addSubscriptionButtonActionPerformed

    private void saveStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStateButtonActionPerformed
        distributor.saveState("state.dat");
        System.out.println("save state is successfull.");
        message.setText("save state is successfull.");
    }//GEN-LAST:event_saveStateButtonActionPerformed

    private void loadStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStateButtonActionPerformed
        distributor.loadState("state.dat");
        System.out.println("load state is successfull.");
        message.setText("load state is successfull.");
    }//GEN-LAST:event_loadStateButtonActionPerformed

    private void listIncompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIncompleteButtonActionPerformed
        distributor.listIncompletePayments();
    }//GEN-LAST:event_listIncompleteButtonActionPerformed

    private void searchSubscriberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSubscriberButtonActionPerformed
        String id = idField.getText();
        if(id.isEmpty()){
            message.setText("the subcriber ID textField next to search subscriber button must be filled.");
        }
        else {
            Subscriber subscriber = distributor.searchSubscriber(Integer.parseInt(id));
            if(subscriber == null){
                message.setText("There is not a subscriber with ID: " + id);
                System.out.println("There is not a subscriber with ID: " + id);
            }
            else{
                JTextArea textArea = new JTextArea(subscriber.toString());
                textArea.setEditable(false);
                JScrollPane scrollPane = new JScrollPane(textArea);
                JOptionPane.showMessageDialog(this, scrollPane, "Subscriber with ID: " + id, JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_searchSubscriberButtonActionPerformed

    private void searchJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJournalButtonActionPerformed
        String issn = issnField.getText();
        if(issn.isEmpty()){
            message.setText("the Journal ISSN textField next to search journal button must be filled.");
        }
        else {
            Journal journal = distributor.searchJournal(issn);
            if(journal == null){
                message.setText("There is not a journal with ISSN: " + issn);
                System.out.println("There is not a journal with ISSN: " + issn);
            }
            else{
                JTextArea textArea = new JTextArea(journal.toString());
                textArea.setEditable(false);
                JScrollPane scrollPane = new JScrollPane(textArea);
                JOptionPane.showMessageDialog(this, scrollPane, "Journal with ISSN: " + issn, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_searchJournalButtonActionPerformed

    private void listSubscriberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSubscriberButtonActionPerformed
        String id = idField2.getText();
        if(id.isEmpty()){
            message.setText("the subcriber ID field next to LIST SUBSCRIPTIONS OF SUBSCRIBER button must be filled.");
        }
        else{
            String result = distributor.listSubscriptionsOfSubscriber(Integer.parseInt(id));
            if(result == null){
                message.setText("There is not a subscriber with ID: " + id);
                System.out.println("There is not a subscriber with ID: " + id);
            }
            else{
                JTextArea textArea = new JTextArea(result);
                textArea.setEditable(false);
                JScrollPane scrollPane = new JScrollPane(textArea);
                JOptionPane.showMessageDialog(this, scrollPane, "Subscription List Of Subscriber with ID: " + id, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_listSubscriberButtonActionPerformed

    private void listJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listJournalButtonActionPerformed
        String issn = issnField2.getText();
        if(issn.isEmpty()){
            message.setText("the Journal ISSN textField next to LIST SUBSCRIPTIONS OF JOURNAL button must be filled.");
        }
        else{
            String result = distributor.listSubscriptionsOfJournal(issn);
            if(result == null){
                message.setText("There is not a journal with ISSN: " + issn);
                System.out.println("There is not a journal with ISSN: " + issn);
            }
            else{
                JTextArea textArea = new JTextArea(result);
                textArea.setEditable(false);
                JScrollPane scrollPane = new JScrollPane(textArea);
                JOptionPane.showMessageDialog(this, scrollPane, "Subscription List Of Journal with ISSN: " + issn, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_listJournalButtonActionPerformed

    private void listSendingOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSendingOrdersButtonActionPerformed
        String issn = issnField3.getText();
        String month = monthField.getText();
        String year = yearField.getText();
        if(issn.isEmpty() || month.isEmpty() || year.isEmpty()){
            message.setText("Each textFields next to List Sending Orders button must be filled.");
        }
        else{
            distributor.listSendingOrders(issn, Integer.parseInt(month), Integer.parseInt(year));
        }
    }//GEN-LAST:event_listSendingOrdersButtonActionPerformed

    private void listAllSendingOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllSendingOrdersButtonActionPerformed
        String month = monthField2.getText();
        String year = yearField2.getText();
        if(month.isEmpty() || year.isEmpty()){
            message.setText("Each textFields next to List Sending Orders button must be filled.");
        }
        else{
            distributor.listAllSendingOrders(Integer.parseInt(month), Integer.parseInt(year));
        }
    }//GEN-LAST:event_listAllSendingOrdersButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        Thread thread = new Thread(distributor);
        thread.start();
        try {
            thread.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_reportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJournalButton;
    private javax.swing.JButton addSubscriberButton;
    private javax.swing.JButton addSubscriptionButton;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField2;
    private javax.swing.JTextField issnField;
    private javax.swing.JTextField issnField2;
    private javax.swing.JTextField issnField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton listAllSendingOrdersButton;
    private javax.swing.JButton listIncompleteButton;
    private javax.swing.JButton listJournalButton;
    private javax.swing.JButton listSendingOrdersButton;
    private javax.swing.JButton listSubscriberButton;
    private javax.swing.JButton loadStateButton;
    private javax.swing.JLabel message;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField monthField2;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton saveStateButton;
    private javax.swing.JButton searchJournalButton;
    private javax.swing.JButton searchSubscriberButton;
    private javax.swing.JTextField yearField;
    private javax.swing.JTextField yearField2;
    // End of variables declaration//GEN-END:variables
}
